### ISSUE TITLE
No change in model size after pruning

### ISSUE THREAD

**Issue by panchal2002** [luuyin/OWL#7]
Hey, I wanted to know whether the size of model will be same after pruning or it'll be reduced?
I've tried to prune OPT-125M model but the size of the model is same as before which is 250MB.
Thanks in advance

**Comment by 123Bailey123** [comment]
The model will remain the same size since OWL/SparseGPT/Wanda etc., are all unstructured pruners (parameters are just set to zero) - Use something like [LLM-Pruner](https://github.com/horseee/LLM-Pruner) for structured pruning which will reduce the model size (and quality).
