### ISSUE TITLE
Why reproduced result is different from the one in paper?

### ISSUE THREAD

**Issue by SHUSHENGQIGUI** [luuyin/OWL#8]
Hi,  I am reproducing the llama-7b pruning experiment, but the perplexities after pruning 70% by sparsegpt, wanda, owl w. are different from the result in paper, as table in below:
![image](https://github.com/luuyin/OWL/assets/28890775/bcb020fc-44f7-4f50-8974-32d774e6f11d)

second col is my res, third col is paper's result.
i wander if i miss any point or if hyperparams in this repo are different from ones in paper?

**Comment by luuyin** [comment]
Hi, Thanks for your question. 
I'm unclear about the values presented in your table; could you please clarify what they represent? Additionally, I'd like to confirm whether you are using the LLaMA-V1 model and if you are strictly adhering to the hyperparameters and scripts provided in the README.

**Comment by SHUSHENGQIGUI** [comment]
Thank you for your reply.
ok， I will make my question clear:
1. I am using llama-v1-7b, and i can reproduce the dense result to be the same as the one in paper at 5.68
2. i am strictly adhering code and hyperparams in the ReadMe, for example, owl w,wanda prune 70%: `main.py    \
--model_name_or_path decapoda-research/llama-7b-hf     \
--Lamda 0.08 \
--Hyper_m 5 \
--model baffo32/decapoda-research-llama-7B-hf     \
--prune_method wanda_owl     \
--sparsity_ratio 0.7 \
--sparsity_type unstructured \
--save save_wanda_owl_test/  \
--save_model out/llama-7b/unstructured/wanda_owl/sparse0.7/`
please check if it is correct
3. the table below is comprison between my result and paper:
![image](https://github.com/luuyin/OWL/assets/28890775/347226f0-78a9-42e8-9c04-4ccefa21397c)
I want to know if there are any codes or hyperparameter configurations that I need to modify or add.

**Comment by SHUSHENGQIGUI** [comment]
> Hi, Thanks for your question. I'm unclear about the values presented in your table; could you please clarify what they represent? Additionally, I'd like to confirm whether you are using the LLaMA-V1 model and if you are strictly adhering to the hyperparameters and scripts provided in the README.

Thank you for your reply.
ok， I will make my question clear:
1. I am using llama-v1-7b, and i can reproduce the dense result to be the same as the one in paper at 5.68
2. i am strictly adhering code and hyperparams in the ReadMe, for example, owl w,wanda prune 70%:` python main.py    \ --model_name_or_path decapoda-research/llama-7b-hf     \ --Lamda 0.08 \ --Hyper_m 5 \ --model baffo32/decapoda-research-llama-7B-hf     \ --prune_method wanda_owl     \ --sparsity_ratio 0.7 \ --sparsity_type unstructured \ --save save_wanda_owl_test/  \ --save_model out/llama-7b/unstructured/wanda_owl/sparse0.7/`
please check if it is correct
3. the table below is comprison between my result and paper:
![image](https://github.com/luuyin/OWL/assets/28890775/b2e10616-d890-43d3-b066-307329dbabcb)

I want to know if there are any codes or hyperparameter configurations that I need to modify or add.

**Comment by SHUSHENGQIGUI** [comment]
> Hi, Thanks for your question. I'm unclear about the values presented in your table; could you please clarify what they represent? Additionally, I'd like to confirm whether you are using the LLaMA-V1 model and if you are strictly adhering to the hyperparameters and scripts provided in the README.

https://github.com/luuyin/OWL/issues/8#issue-2309761230

**Comment by SHUSHENGQIGUI** [comment]
> > Hi, Thanks for your question. I'm unclear about the values presented in your table; could you please clarify what they represent? Additionally, I'd like to confirm whether you are using the LLaMA-V1 model and if you are strictly adhering to the hyperparameters and scripts provided in the README.
> 
> Thank you for your reply. ok， I will make my question clear:
> 
> 1. I am using llama-v1-7b, and i can reproduce the dense result to be the same as the one in paper at 5.68
> 2. i am strictly adhering code and hyperparams in the ReadMe, for example, owl w,wanda prune 70%:` python main.py    \ --model_name_or_path decapoda-research/llama-7b-hf     \ --Lamda 0.08 \ --Hyper_m 5 \ --model baffo32/decapoda-research-llama-7B-hf     \ --prune_method wanda_owl     \ --sparsity_ratio 0.7 \ --sparsity_type unstructured \ --save save_wanda_owl_test/  \ --save_model out/llama-7b/unstructured/wanda_owl/sparse0.7/`
>    please check if it is correct
> 3. the table below is comprison between my result and paper:
>    ![image](https://private-user-images.githubusercontent.com/28890775/333013771-b2e10616-d890-43d3-b066-307329dbabcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTE1NzksIm5iZiI6MTcxNjcxMTI3OSwicGF0aCI6Ii8yODg5MDc3NS8zMzMwMTM3NzEtYjJlMTA2MTYtZDg5MC00M2QzLWIwNjYtMzA3MzI5ZGJhYmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA4MTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NDE3ODNjOGUxNTViN2NjZWRmMjM4MzY0NjM4NTkyMDJmOTliZWMwNDFiNWY1MmI4ZmFjZjI5MDIyNTg5MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vrjL3dLqcSNEDT2jutdYKuQOrMXKhRfwF7zcihcTdWQ)
> 
> I want to know if there are any codes or hyperparameter configurations that I need to modify or add.

@luuyin hi,  could you reply to me in your spare time ? i am stuck in this problem. I don't know how i reproduce the result as showed in paper. please
